// <auto-generated />
namespace InOne.Reservation.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201909231311076_4Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
